// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID        int16
	Name      string
	IsActive  pgtype.Bool
	IsDeleted pgtype.Bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Message struct {
	ID             int16
	ParticipantID  int32
	ConversationID int32
	Type           int32
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Participant struct {
	ID        int16
	UserID    int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID          int16
	FirstName   string
	MiddleName  pgtype.Text
	LastName    string
	Birthday    pgtype.Timestamp
	Username    string
	Password    string
	Email       pgtype.Text
	PhoneNumber pgtype.Text
	Gender      pgtype.Text
	IsActive    pgtype.Bool
	IsDeleted   pgtype.Bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
